name: Nightly

on:
  workflow_dispatch:
    inputs:
      build-ubuntu:
        description: 'Build Ubuntu'
        type: boolean
        default: true
      build-windows:
        description: 'Build Windows'
        type: boolean
        default: true
      build-mac:
        description: 'Build macOS'
        type: boolean
        default: true

permissions: {}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Build OS matrix
        id: set-matrix
        run: |
          os_list=()
          if [ "${{ github.event.inputs.build-ubuntu }}" == "true" ]; then
            os_list+=("\"ubuntu-latest\"")
          fi
          if [ "${{ github.event.inputs.build-windows }}" == "true" ]; then
            os_list+=("\"windows-latest\"")
          fi
          if [ "${{ github.event.inputs.build-mac }}" == "true" ]; then
            os_list+=("\"macos-latest\"")
          fi
          joined=$(IFS=,; echo "${os_list[*]}")
          echo "matrix={\"os\":[$joined]}" >> "$GITHUB_OUTPUT"

  build:
    needs: prepare
    if: ${{ needs.prepare.outputs.matrix != '{"os":[]}' }}
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Install dependencies
        run: npm run requirement

      - name: Build VencordExtension
        run: npm run vencord

      - name: Build Discohook Editor
        run: npm run discohook

      - name: Build JS Code
        run: npm run build:ts

      - name: Build Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          github_token: ${{ secrets.github_token }}
          release: false

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DiscordBotClient-nightly-${{ matrix.os }}
          retention-days: 1
          path: |
            dist/*.exe
            dist/*.AppImage
            dist/*.dmg
